// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wheel_commands.proto

#include "wheel_commands.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace luggage_av {
PROTOBUF_CONSTEXPR WheelCommands::WheelCommands(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.velocity_left_)*/0
  , /*decltype(_impl_.velocity_right_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WheelCommandsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WheelCommandsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WheelCommandsDefaultTypeInternal() {}
  union {
    WheelCommands _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WheelCommandsDefaultTypeInternal _WheelCommands_default_instance_;
}  // namespace luggage_av
static ::_pb::Metadata file_level_metadata_wheel_5fcommands_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_wheel_5fcommands_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_wheel_5fcommands_2eproto = nullptr;

const uint32_t TableStruct_wheel_5fcommands_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::luggage_av::WheelCommands, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::luggage_av::WheelCommands, _impl_.velocity_left_),
  PROTOBUF_FIELD_OFFSET(::luggage_av::WheelCommands, _impl_.velocity_right_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::luggage_av::WheelCommands)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::luggage_av::_WheelCommands_default_instance_._instance,
};

const char descriptor_table_protodef_wheel_5fcommands_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024wheel_commands.proto\022\nluggage_av\">\n\rWh"
  "eelCommands\022\025\n\rvelocity_left\030\001 \001(\021\022\026\n\016ve"
  "locity_right\030\002 \001(\021b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_wheel_5fcommands_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_wheel_5fcommands_2eproto = {
    false, false, 106, descriptor_table_protodef_wheel_5fcommands_2eproto,
    "wheel_commands.proto",
    &descriptor_table_wheel_5fcommands_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_wheel_5fcommands_2eproto::offsets,
    file_level_metadata_wheel_5fcommands_2eproto, file_level_enum_descriptors_wheel_5fcommands_2eproto,
    file_level_service_descriptors_wheel_5fcommands_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_wheel_5fcommands_2eproto_getter() {
  return &descriptor_table_wheel_5fcommands_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_wheel_5fcommands_2eproto(&descriptor_table_wheel_5fcommands_2eproto);
namespace luggage_av {

// ===================================================================

class WheelCommands::_Internal {
 public:
};

WheelCommands::WheelCommands(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:luggage_av.WheelCommands)
}
WheelCommands::WheelCommands(const WheelCommands& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WheelCommands* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.velocity_left_){}
    , decltype(_impl_.velocity_right_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.velocity_left_, &from._impl_.velocity_left_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.velocity_right_) -
    reinterpret_cast<char*>(&_impl_.velocity_left_)) + sizeof(_impl_.velocity_right_));
  // @@protoc_insertion_point(copy_constructor:luggage_av.WheelCommands)
}

inline void WheelCommands::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.velocity_left_){0}
    , decltype(_impl_.velocity_right_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

WheelCommands::~WheelCommands() {
  // @@protoc_insertion_point(destructor:luggage_av.WheelCommands)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WheelCommands::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void WheelCommands::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WheelCommands::Clear() {
// @@protoc_insertion_point(message_clear_start:luggage_av.WheelCommands)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.velocity_left_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.velocity_right_) -
      reinterpret_cast<char*>(&_impl_.velocity_left_)) + sizeof(_impl_.velocity_right_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WheelCommands::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // sint32 velocity_left = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.velocity_left_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 velocity_right = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.velocity_right_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WheelCommands::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:luggage_av.WheelCommands)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // sint32 velocity_left = 1;
  if (this->_internal_velocity_left() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(1, this->_internal_velocity_left(), target);
  }

  // sint32 velocity_right = 2;
  if (this->_internal_velocity_right() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(2, this->_internal_velocity_right(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:luggage_av.WheelCommands)
  return target;
}

size_t WheelCommands::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:luggage_av.WheelCommands)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // sint32 velocity_left = 1;
  if (this->_internal_velocity_left() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_velocity_left());
  }

  // sint32 velocity_right = 2;
  if (this->_internal_velocity_right() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_velocity_right());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WheelCommands::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WheelCommands::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WheelCommands::GetClassData() const { return &_class_data_; }


void WheelCommands::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WheelCommands*>(&to_msg);
  auto& from = static_cast<const WheelCommands&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:luggage_av.WheelCommands)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_velocity_left() != 0) {
    _this->_internal_set_velocity_left(from._internal_velocity_left());
  }
  if (from._internal_velocity_right() != 0) {
    _this->_internal_set_velocity_right(from._internal_velocity_right());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WheelCommands::CopyFrom(const WheelCommands& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:luggage_av.WheelCommands)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WheelCommands::IsInitialized() const {
  return true;
}

void WheelCommands::InternalSwap(WheelCommands* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WheelCommands, _impl_.velocity_right_)
      + sizeof(WheelCommands::_impl_.velocity_right_)
      - PROTOBUF_FIELD_OFFSET(WheelCommands, _impl_.velocity_left_)>(
          reinterpret_cast<char*>(&_impl_.velocity_left_),
          reinterpret_cast<char*>(&other->_impl_.velocity_left_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WheelCommands::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_wheel_5fcommands_2eproto_getter, &descriptor_table_wheel_5fcommands_2eproto_once,
      file_level_metadata_wheel_5fcommands_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace luggage_av
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::luggage_av::WheelCommands*
Arena::CreateMaybeMessage< ::luggage_av::WheelCommands >(Arena* arena) {
  return Arena::CreateMessageInternal< ::luggage_av::WheelCommands >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
