// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wheel_commands.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wheel_5fcommands_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wheel_5fcommands_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wheel_5fcommands_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wheel_5fcommands_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wheel_5fcommands_2eproto;
namespace luggage_av {
class WheelCommands;
struct WheelCommandsDefaultTypeInternal;
extern WheelCommandsDefaultTypeInternal _WheelCommands_default_instance_;
}  // namespace luggage_av
PROTOBUF_NAMESPACE_OPEN
template<> ::luggage_av::WheelCommands* Arena::CreateMaybeMessage<::luggage_av::WheelCommands>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace luggage_av {

// ===================================================================

class WheelCommands final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:luggage_av.WheelCommands) */ {
 public:
  inline WheelCommands() : WheelCommands(nullptr) {}
  ~WheelCommands() override;
  explicit PROTOBUF_CONSTEXPR WheelCommands(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WheelCommands(const WheelCommands& from);
  WheelCommands(WheelCommands&& from) noexcept
    : WheelCommands() {
    *this = ::std::move(from);
  }

  inline WheelCommands& operator=(const WheelCommands& from) {
    CopyFrom(from);
    return *this;
  }
  inline WheelCommands& operator=(WheelCommands&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WheelCommands& default_instance() {
    return *internal_default_instance();
  }
  static inline const WheelCommands* internal_default_instance() {
    return reinterpret_cast<const WheelCommands*>(
               &_WheelCommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WheelCommands& a, WheelCommands& b) {
    a.Swap(&b);
  }
  inline void Swap(WheelCommands* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WheelCommands* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WheelCommands* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WheelCommands>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WheelCommands& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WheelCommands& from) {
    WheelCommands::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WheelCommands* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "luggage_av.WheelCommands";
  }
  protected:
  explicit WheelCommands(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVelocityLeftFieldNumber = 1,
    kVelocityRightFieldNumber = 2,
  };
  // sint32 velocity_left = 1;
  void clear_velocity_left();
  int32_t velocity_left() const;
  void set_velocity_left(int32_t value);
  private:
  int32_t _internal_velocity_left() const;
  void _internal_set_velocity_left(int32_t value);
  public:

  // sint32 velocity_right = 2;
  void clear_velocity_right();
  int32_t velocity_right() const;
  void set_velocity_right(int32_t value);
  private:
  int32_t _internal_velocity_right() const;
  void _internal_set_velocity_right(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:luggage_av.WheelCommands)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t velocity_left_;
    int32_t velocity_right_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_wheel_5fcommands_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WheelCommands

// sint32 velocity_left = 1;
inline void WheelCommands::clear_velocity_left() {
  _impl_.velocity_left_ = 0;
}
inline int32_t WheelCommands::_internal_velocity_left() const {
  return _impl_.velocity_left_;
}
inline int32_t WheelCommands::velocity_left() const {
  // @@protoc_insertion_point(field_get:luggage_av.WheelCommands.velocity_left)
  return _internal_velocity_left();
}
inline void WheelCommands::_internal_set_velocity_left(int32_t value) {
  
  _impl_.velocity_left_ = value;
}
inline void WheelCommands::set_velocity_left(int32_t value) {
  _internal_set_velocity_left(value);
  // @@protoc_insertion_point(field_set:luggage_av.WheelCommands.velocity_left)
}

// sint32 velocity_right = 2;
inline void WheelCommands::clear_velocity_right() {
  _impl_.velocity_right_ = 0;
}
inline int32_t WheelCommands::_internal_velocity_right() const {
  return _impl_.velocity_right_;
}
inline int32_t WheelCommands::velocity_right() const {
  // @@protoc_insertion_point(field_get:luggage_av.WheelCommands.velocity_right)
  return _internal_velocity_right();
}
inline void WheelCommands::_internal_set_velocity_right(int32_t value) {
  
  _impl_.velocity_right_ = value;
}
inline void WheelCommands::set_velocity_right(int32_t value) {
  _internal_set_velocity_right(value);
  // @@protoc_insertion_point(field_set:luggage_av.WheelCommands.velocity_right)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace luggage_av

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wheel_5fcommands_2eproto
