luggage_av:
  sllidar_node:
    ros__parameters:
      channel_type: serial
      serial_port: /dev/ttyUSB0
      serial_baudrate: 115200
      frame_id: luggage_av/laser
      inverted: False
      angle_compensate: True
      # scan_mode: Sensitivity