<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="params.xacro" />

    <material name="lidar_black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="lidar_blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <xacro:property name="lidar_pole_x_origin" value="${-chassis_length/2}" />
    <xacro:property name="lidar_pole_y_origin" value="${chassis_width/2}" />
    <xacro:property name="lidar_pole_z_origin" value="${chassis_height - drive_wheel_radius + chassis_Z_offset}" />

    <joint name="lidar_mount_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_mount_link"/>
        <origin xyz = "${lidar_pole_x_origin+lidar_pole_length/2 + chassis_X_offset} ${lidar_pole_y_origin-lidar_pole_width/2} ${lidar_pole_z_origin + lidar_pole_height/2}"/>
    </joint>

    <link name="lidar_mount_link">
        <visual>
            <origin xyz = "0 0 0"/>
            <geometry>
                <box size="${lidar_pole_length} ${lidar_pole_width} ${lidar_pole_height}"/>
            </geometry>
            <material name="lidar_black"/>
        </visual>
        <collision>
            <origin xyz = "0 0 0"/>
            <geometry>
                <box size="${lidar_pole_length} ${lidar_pole_width} ${lidar_pole_height}"/>
            </geometry>
            <material name="lidar_black"/>
        </collision>
        <xacro:inertial_box mass="0.1" x="${lidar_pole_length}" y="${lidar_pole_width}" z="${lidar_pole_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="lidar_mount_link"/>
        <child link="laser"/>
        <origin xyz = "0 0 ${(lidar_pole_height+lidar_sensor_height)/2}"/> <!--half the height of the mount + half the height of the lidar itself -->
    </joint>

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${lidar_sensor_radius}" length="${lidar_sensor_radius}"/>
            </geometry>
            <material name="lidar_blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_sensor_radius}" length="${lidar_sensor_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${lidar_sensor_radius}" length="${lidar_sensor_radius}" >
            <origin xyz="0 0 ${(lidar_pole_height+lidar_sensor_height)/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="laser">
        <material>Gazebo/blue</material>

        <sensor name="laser" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </lidar>
            <topic>scan</topic>
            <gz_frame_id>luggage_av/laser</gz_frame_id>
        </sensor>
    </gazebo>

</robot>