<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="params.xacro" />

    <material name="lidar_black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="lidar_burgundy">
        <color rgba="0.5 0 0.125 0.8"/>
    </material>

    <joint name="lidar_mount_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_mount_link"/>
        <origin xyz = "${lidar_pole_x_offset} ${lidar_pole_y_offset} ${lidar_pole_z_offset}"/>
    </joint>

    <link name="lidar_mount_link">
        <visual>
            <origin xyz="${-lidar_pole_length/2} ${-lidar_pole_width/2} ${lidar_pole_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${lidar_pole_length} ${lidar_pole_width} ${lidar_pole_height}"/>
            </geometry>
            <material name="lidar_black"/>
        </visual>
        <collision>
            <origin xyz="${-lidar_pole_length/2} ${-lidar_pole_width/2} ${lidar_pole_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${lidar_pole_length} ${lidar_pole_width} ${lidar_pole_height}"/>
            </geometry>
            <material name="lidar_black"/>
        </collision>
        <xacro:inertial_box mass="0.1" x="${lidar_pole_length}" y="${lidar_pole_width}" z="${lidar_pole_height}">
            <origin xyz="${-lidar_pole_length/2} ${-lidar_pole_width/2} ${lidar_pole_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="lidar_mount_link"/>
        <child link="base_laser"/>
        <origin xyz="${lidar_sensor_x_offset} ${lidar_sensor_y_offset} ${lidar_sensor_z_offset}" rpy="0 0 ${pi/2}"/> <!--half the height of the mount + half the height of the lidar itself -->
    </joint>

    <link name="base_laser">
        <visual>
            <origin xyz="0 0 ${lidar_sensor_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_sensor_radius}" length="${lidar_sensor_radius}"/>
            </geometry>
            <material name="lidar_burgundy"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${lidar_sensor_height/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${lidar_sensor_radius}" length="${lidar_sensor_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${lidar_sensor_radius}" length="${lidar_sensor_radius}" >
            <origin xyz="0 0 ${lidar_sensor_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="base_laser">
        <material>Gazebo/blue</material>

        <sensor name="lidar" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </lidar>
            <topic>scan</topic>
            <gz_frame_id>$(arg namespace)/base_laser</gz_frame_id>
        </sensor>
    </gazebo>

</robot>
